{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations-{{ .Release.Revision }}
  annotations:
    # Helm hook: запускается перед установкой/обновлением
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    # Удаляем старые Jobs после успешного выполнения
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: django-migrations
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        app: django-migrations
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: dockerhub-credentials
      initContainers:
      # Ждем, пока PostgreSQL будет готов
      - name: wait-for-postgres
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z postgres-service 5432; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is up"
      {{- if .Values.elasticsearch.enabled }}
      # Ждем, пока Elasticsearch будет готов
      - name: wait-for-elasticsearch
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for Elasticsearch to be ready..."
          until wget -q --spider http://elasticsearch-service:9200/_cluster/health; do
            echo "Elasticsearch is unavailable - sleeping"
            sleep 5
          done
          echo "Elasticsearch is up"
      {{- end }}
      containers:
      - name: django-migrate
        image: "{{ .Values.djangoApp.image.repository }}:{{ .Values.djangoApp.image.tag }}"
        imagePullPolicy: {{ .Values.djangoApp.image.pullPolicy }}
        command:
        - sh
        - -c
        - |
          echo "Starting Django migrations..."
          python manage.py migrate --noinput
          {{- if .Values.migrations.collectstatic }}
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          {{- end }}
          echo "Migrations completed successfully!"
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
        envFrom:
        - secretRef:
            name: {{ .Values.secretsName }}
        - configMapRef:
            name: {{ .Values.configMapName }}
{{- end }}
