{{- if .Values.rabbitmq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: {{ .Values.rabbitmq.service.amqpPort }}
    targetPort: 5672
  - name: management
    port: {{ .Values.rabbitmq.service.managementPort }}
    targetPort: 15672
{{- end -}}
