apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-django-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sg12/argocd.git
    targetRevision: HEAD
    path: apps/my-django-app-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
