apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osrm-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sg12/argocd.git
    targetRevision: HEAD
    path: osrm

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
