{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: NodePort # <-- Указываем тип сервиса
  selector:
    app: postgres # Находит поды с меткой app=postgres
  ports:
    - protocol: TCP
      # --- Внутренняя работа кластера ---
      port: {{ .Values.postgres.service.port }} # Внутренний порт сервиса (можно оставить стандартным)
      targetPort: 5432 # Порт на поде, куда отправлять трафик (тоже стандартный)
      # --- Внешний доступ ---
      nodePort: 30432 # <-- ВАШ НЕСТАНДАРТНЫЙ ПОРТ!
                      # Kubernetes выставит этот порт на IP-адресе вашего сервера.
                      # Выбирайте любой порт в диапазоне 30000-32767
{{- end -}}
